### ISSUE TITLE
Beginner friendly intro

### ISSUE THREAD

**Issue by jsaade** [hypersurge/awe6#22]
The current installation instructions and tutorials are not beginner friendly at all.
Especially to people new to haxe.

How do you compile? The helloworld example just has a bunch of commands but no instructions on where to use them (I am on mac)?

In addition, the demos are not compiled (if I run the .htm files included it says missing files like game.js).

Thanks

**Comment by hypersurge** [comment]
Thanks for your feedback.

I've tweaked [HelloWorld](https://github.com/hypersurge/awe6/wiki/Example-HelloWorld) to remove the need for HXML (a Haxe compiler markup language) and made reference to using [Haxe](http://haxe.org/documentation/introduction/language-introduction.html).  Please let me know if the example makes more sense now.

The Demos are not exactly exciting, and used more for testing purposes.  Their compiled output is not pushed to Github (else every commit would be bloated).  Instead [see these](https://github.com/hypersurge/awe6/tree/master/docs/demos).

The Demos do currently rely on FlashDevelop to build - it doesn't come much easier than this for Windows, but I can see it is unhelpful for Mac users.  I will add HXML or command line notes as alternatives.

**Comment by hypersurge** [comment]
Command line hints added to README.md for each demo project.  Also see [samples](https://github.com/hypersurge/awe6/tree/master/samples) for more.

**Comment by jsaade** [comment]
Thanks a lot for the fast response.
