### ISSUE TITLE
API page broken on all browsers

### ISSUE THREAD

**Issue by bedwardly-down** [hypersurge/awe6#35]
First of all, the fact that awe6 is still alive surprised me but is super awesome. It’s what i cut my teeth on for Haxe. Kudos.

Secondly, I’m glad there’s finally actual documentation. Last time i messed with awe6 was like 5 years ago or so. The problem, the API docs page is rendering blank on mobile and showing “content missing” on desktop.

![D962715E-71AA-4D01-BBD2-69CCCE067378](https://user-images.githubusercontent.com/59133880/79025471-7aba1300-7b4b-11ea-8602-8c3122139698.png)

**Comment by hypersurge** [comment]
Thanks for reporting this.  Looks like the Frame was confusing the redirects.  I've set up Github Pages so the new API link is https://hypersurge.github.io/awe6/api/

I've changed other API urls where I saw them (on the wiki).

Please note awe6 from haxelib has a few minor Haxe 4 issues, which can be patched from the repo.  A new haxelib release is imminent.

**Comment by bedwardly-down** [comment]
Thanks for getting in that as far as you had. Now, if there was a more active and updated forum. Ha

**Comment by hypersurge** [comment]
In 2020 I don't really see any evidence that anyone is using this besides our team?  We continue to use it commercially on a day-to-day basis (and produce a few HTML5 games a month).  It still works well for us, and we've developed many custom layers on top - but I'm not sure I'd recommend awe6 to anyone who doesn't already have both an understanding and a legacy to it?

**Comment by bedwardly-down** [comment]
Fair points. I’ve always had a fondness of obscure software and just not following the norm. I kind of wanna try to build something using awe6 because back when i found it, I loved how weird its approach was but was too wet at the time to understand how to read the code and build from just figuring it out. If all else fails, both pixijs and createjs seem interesting enough to make this worth it.
