### ISSUE TITLE
Not everyone's on Windows

### ISSUE THREAD

**Issue by jgedri** [hypersurge/awe6#40]
There should be an alternative to loading a .hxproject file to build one of the demos. This is an _open source_ project, but it's biased towards a program that only runs on Windows.

**Comment by hypersurge** [comment]
Not biased at all, Windows is optional.  The README.md file that accompanies each demo / sample includes the build command line.

**Comment by Brian151** [comment]
and aren't haxe and flash develop also both open-source?

**Comment by hypersurge** [comment]
Yes they are (with FlashDevelop/HaxeDevelop becoming stale / stable) - however I didn't interpret that as the issue.
I read it as "I don't run Windows and I'm new to Haxe - how can I compile the demo?".

**Comment by jgedri** [comment]
> and aren't haxe and flash develop also both open-source?

They are, but I'm by no means a professional coder. By myself I would not be able to port a whole app to Linux.

There seem to be very few examples for awe6 unless you count those commercial games by Hypersurge, and looking at the API docs doesn't really help me.

**Comment by hypersurge** [comment]
> There seem to be very few examples for awe6 unless you count those commercial games by Hypersurge, and looking at the API docs doesn't really help me.

There are 100+ awe6 games professionally developed and published from our studio.  It works well for us, I can't say where else it is still used directly, but let's assume small numbers.  By comparison there could be a million games made with the widely adopted Phaser CE, which has many tutorials, but also an opinionated approach.  Typically the two go hand in hand - because it's hard to tutorialise generalisations.  Whereas APIs, code, design patterns, debate ... these are the doors to the bigger vault.

**Comment by jgedri** [comment]
Thanks for replying so quickly. I was going to use the contact form, but it insisted I didn't put in a valid email. What I want to know is: Does licensing a game get me access to its source code?

**Comment by hypersurge** [comment]
> Does licensing a game get me access to its source code?

A general answer is that commercial licenses tend to vary based on intent, territory, and duration.  For example you may be interested in licensing derivative rights to a proprietary game that extends an open-source framework (like awe6)?  Probably best to drop an email or DM to the rights holder directly and explain what you want to do and why.

**Comment by jgedri** [comment]
Sorry, I was thinking of b10b. And I just want an example of a finished, complex game instead of yet another "hello world".

**Comment by Brian151** [comment]
> 
> 
> Sorry, I was thinking of b10b. And I just want an example of a finished, complex game instead of yet another "hello world".

pretty sure there's a link/button on the b10b game's page to license the games, not sure what that entails however.

i do agree, so much...
tutorials in a way actually have a tendency to set-you up for failure and to learn bad techniques
they also time and time again are outdated when you find them [or specifically use older versions of the language/tools/framework to begin with]. official documentations are often hit-and-miss, too... 

be that as it may, the expectation always was if you wanted a full game that you code it up yourselves. there was a time developers made this work with little/no information or even by completely reverse-engineering game consoles! [and not saying i discourage learning from or adapting from a fully developed project, a lot of people do that.] some games you might find decompilers useful for. [flash/java/android especially] HTML5 games can sometimes also have their javascript source viewed, but minimization and obfuscation are often used with those.

**Comment by hypersurge** [comment]
I'm going to close this issue as I think it was (always?) resolved.  If related tasks arise please feel free to open a new issue and reference this as needed.
